// Code generated by options-gen v0.58.0. DO NOT EDIT.

package adminapp

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	eventstream "github.com/assurrussa/gowebsocket/eventstream"
	"github.com/gofiber/fiber/v3/middleware/session"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	goinertia "github.com/assurrussa/goadmin/infrastructure/inertia"
	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
	"github.com/assurrussa/goadmin/services/adminservice"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	httpManager *goinertia.Inertia,
	permissionGuard PermissionGuard,
	rolesService RolesService,
	adminAuth *adminservice.Service,
	session *session.Store,
	eventStream eventstream.EventStream,
	outbox OutboxPutter,
	txManager outbox.StoragePgsqlTxManager,
	logger logger.Logger,
	env string,
	filesBaseURL string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.httpManager = httpManager
	o.permissionGuard = permissionGuard
	o.rolesService = rolesService
	o.adminAuth = adminAuth
	o.session = session
	o.eventStream = eventStream
	o.outbox = outbox
	o.txManager = txManager
	o.logger = logger
	o.env = env
	o.filesBaseURL = filesBaseURL

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithFilesBucket(opt string) OptOptionsSetter {
	return func(o *Options) { o.filesBucket = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("httpManager", _validate_Options_httpManager(o)))
	errs.Add(errors461e464ebed9.NewValidationError("permissionGuard", _validate_Options_permissionGuard(o)))
	errs.Add(errors461e464ebed9.NewValidationError("rolesService", _validate_Options_rolesService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("adminAuth", _validate_Options_adminAuth(o)))
	errs.Add(errors461e464ebed9.NewValidationError("session", _validate_Options_session(o)))
	errs.Add(errors461e464ebed9.NewValidationError("txManager", _validate_Options_txManager(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("env", _validate_Options_env(o)))
	errs.Add(errors461e464ebed9.NewValidationError("filesBaseURL", _validate_Options_filesBaseURL(o)))
	errs.Add(errors461e464ebed9.NewValidationError("filesBucket", _validate_Options_filesBucket(o)))
	return errs.AsError()
}

func _validate_Options_httpManager(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.httpManager, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `httpManager` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_permissionGuard(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.permissionGuard, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `permissionGuard` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_rolesService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.rolesService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `rolesService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_adminAuth(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.adminAuth, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `adminAuth` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_session(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.session, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `session` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_txManager(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.txManager, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `txManager` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_env(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.env, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `env` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_filesBaseURL(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.filesBaseURL, "omitempty,url"); err != nil {
		return fmt461e464ebed9.Errorf("field `filesBaseURL` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_filesBucket(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.filesBucket, "omitempty"); err != nil {
		return fmt461e464ebed9.Errorf("field `filesBucket` did not pass the test: %w", err)
	}
	return nil
}
