// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/repo_mock.gen.go -package=jobsfailedrepomocks
//

// Package jobsfailedrepomocks is a generated GoMock package.
package jobsfailedrepomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
)

// MockjobsFailedRepository is a mock of jobsFailedRepository interface.
type MockjobsFailedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockjobsFailedRepositoryMockRecorder
	isgomock struct{}
}

// MockjobsFailedRepositoryMockRecorder is the mock recorder for MockjobsFailedRepository.
type MockjobsFailedRepositoryMockRecorder struct {
	mock *MockjobsFailedRepository
}

// NewMockjobsFailedRepository creates a new mock instance.
func NewMockjobsFailedRepository(ctrl *gomock.Controller) *MockjobsFailedRepository {
	mock := &MockjobsFailedRepository{ctrl: ctrl}
	mock.recorder = &MockjobsFailedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobsFailedRepository) EXPECT() *MockjobsFailedRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockjobsFailedRepository) All(ctx context.Context) ([]outbox.JobFailedModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]outbox.JobFailedModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockjobsFailedRepositoryMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockjobsFailedRepository)(nil).All), ctx)
}

// CountLight mocks base method.
func (m *MockjobsFailedRepository) CountLight(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLight", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLight indicates an expected call of CountLight.
func (mr *MockjobsFailedRepositoryMockRecorder) CountLight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLight", reflect.TypeOf((*MockjobsFailedRepository)(nil).CountLight), ctx)
}

// Create mocks base method.
func (m *MockjobsFailedRepository) Create(ctx context.Context, job outbox.JobFailedModel) (outbox.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(outbox.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockjobsFailedRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockjobsFailedRepository)(nil).Create), ctx, job)
}

// Delete mocks base method.
func (m *MockjobsFailedRepository) Delete(ctx context.Context, jobID outbox.JobID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, jobID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockjobsFailedRepositoryMockRecorder) Delete(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockjobsFailedRepository)(nil).Delete), ctx, jobID)
}

// GetByID mocks base method.
func (m *MockjobsFailedRepository) GetByID(ctx context.Context, id outbox.JobID) (outbox.JobFailedModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(outbox.JobFailedModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockjobsFailedRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockjobsFailedRepository)(nil).GetByID), ctx, id)
}
