// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.gen.go -package=queuesmocks
//

// Package queuesmocks is a generated GoMock package.
package queuesmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	datagrid "github.com/assurrussa/goadmin/infrastructure/core/datagrid"
	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
)

// MockjobsRepository is a mock of jobsRepository interface.
type MockjobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockjobsRepositoryMockRecorder
	isgomock struct{}
}

// MockjobsRepositoryMockRecorder is the mock recorder for MockjobsRepository.
type MockjobsRepositoryMockRecorder struct {
	mock *MockjobsRepository
}

// NewMockjobsRepository creates a new mock instance.
func NewMockjobsRepository(ctrl *gomock.Controller) *MockjobsRepository {
	mock := &MockjobsRepository{ctrl: ctrl}
	mock.recorder = &MockjobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobsRepository) EXPECT() *MockjobsRepositoryMockRecorder {
	return m.recorder
}

// CountExact mocks base method.
func (m *MockjobsRepository) CountExact(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExact", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExact indicates an expected call of CountExact.
func (mr *MockjobsRepositoryMockRecorder) CountExact(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExact", reflect.TypeOf((*MockjobsRepository)(nil).CountExact), ctx)
}

// Create mocks base method.
func (m *MockjobsRepository) Create(ctx context.Context, job outbox.JobModel) (outbox.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(outbox.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockjobsRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockjobsRepository)(nil).Create), ctx, job)
}

// DeleteJob mocks base method.
func (m *MockjobsRepository) DeleteJob(ctx context.Context, jobID outbox.JobID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteJob", ctx, jobID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteJob indicates an expected call of DeleteJob.
func (mr *MockjobsRepositoryMockRecorder) DeleteJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteJob", reflect.TypeOf((*MockjobsRepository)(nil).DeleteJob), ctx, jobID)
}

// GetList mocks base method.
func (m *MockjobsRepository) GetList(ctx context.Context, filtered datagrid.Filtered) ([]outbox.JobModel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filtered)
	ret0, _ := ret[0].([]outbox.JobModel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockjobsRepositoryMockRecorder) GetList(ctx, filtered any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockjobsRepository)(nil).GetList), ctx, filtered)
}

// MockjobsFailedRepository is a mock of jobsFailedRepository interface.
type MockjobsFailedRepository struct {
	ctrl     *gomock.Controller
	recorder *MockjobsFailedRepositoryMockRecorder
	isgomock struct{}
}

// MockjobsFailedRepositoryMockRecorder is the mock recorder for MockjobsFailedRepository.
type MockjobsFailedRepositoryMockRecorder struct {
	mock *MockjobsFailedRepository
}

// NewMockjobsFailedRepository creates a new mock instance.
func NewMockjobsFailedRepository(ctrl *gomock.Controller) *MockjobsFailedRepository {
	mock := &MockjobsFailedRepository{ctrl: ctrl}
	mock.recorder = &MockjobsFailedRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobsFailedRepository) EXPECT() *MockjobsFailedRepositoryMockRecorder {
	return m.recorder
}

// CountExact mocks base method.
func (m *MockjobsFailedRepository) CountExact(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountExact", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountExact indicates an expected call of CountExact.
func (mr *MockjobsFailedRepositoryMockRecorder) CountExact(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountExact", reflect.TypeOf((*MockjobsFailedRepository)(nil).CountExact), ctx)
}

// Delete mocks base method.
func (m *MockjobsFailedRepository) Delete(ctx context.Context, jobID outbox.JobID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, jobID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Delete indicates an expected call of Delete.
func (mr *MockjobsFailedRepositoryMockRecorder) Delete(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockjobsFailedRepository)(nil).Delete), ctx, jobID)
}

// GetByID mocks base method.
func (m *MockjobsFailedRepository) GetByID(ctx context.Context, id outbox.JobID) (outbox.JobFailedModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(outbox.JobFailedModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockjobsFailedRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockjobsFailedRepository)(nil).GetByID), ctx, id)
}

// GetList mocks base method.
func (m *MockjobsFailedRepository) GetList(ctx context.Context, filtered datagrid.Filtered) ([]outbox.JobFailedModel, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filtered)
	ret0, _ := ret[0].([]outbox.JobFailedModel)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockjobsFailedRepositoryMockRecorder) GetList(ctx, filtered any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockjobsFailedRepository)(nil).GetList), ctx, filtered)
}
