// Code generated by MockGen. DO NOT EDIT.
// Source: repo.go
//
// Generated by this command:
//
//	mockgen -source=repo.go -destination=mocks/repo_mock.gen.go -package=jobsrepomocks
//

// Package jobsrepomocks is a generated GoMock package.
package jobsrepomocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
)

// MockjobsRepository is a mock of jobsRepository interface.
type MockjobsRepository struct {
	ctrl     *gomock.Controller
	recorder *MockjobsRepositoryMockRecorder
	isgomock struct{}
}

// MockjobsRepositoryMockRecorder is the mock recorder for MockjobsRepository.
type MockjobsRepositoryMockRecorder struct {
	mock *MockjobsRepository
}

// NewMockjobsRepository creates a new mock instance.
func NewMockjobsRepository(ctrl *gomock.Controller) *MockjobsRepository {
	mock := &MockjobsRepository{ctrl: ctrl}
	mock.recorder = &MockjobsRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockjobsRepository) EXPECT() *MockjobsRepositoryMockRecorder {
	return m.recorder
}

// All mocks base method.
func (m *MockjobsRepository) All(ctx context.Context) ([]outbox.JobModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "All", ctx)
	ret0, _ := ret[0].([]outbox.JobModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// All indicates an expected call of All.
func (mr *MockjobsRepositoryMockRecorder) All(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "All", reflect.TypeOf((*MockjobsRepository)(nil).All), ctx)
}

// CountLight mocks base method.
func (m *MockjobsRepository) CountLight(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountLight", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountLight indicates an expected call of CountLight.
func (mr *MockjobsRepositoryMockRecorder) CountLight(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountLight", reflect.TypeOf((*MockjobsRepository)(nil).CountLight), ctx)
}

// Create mocks base method.
func (m *MockjobsRepository) Create(ctx context.Context, job outbox.JobModel) (outbox.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, job)
	ret0, _ := ret[0].(outbox.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockjobsRepositoryMockRecorder) Create(ctx, job any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockjobsRepository)(nil).Create), ctx, job)
}

// GetByID mocks base method.
func (m *MockjobsRepository) GetByID(ctx context.Context, id outbox.JobID) (outbox.JobModel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(outbox.JobModel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockjobsRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockjobsRepository)(nil).GetByID), ctx, id)
}
