// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/seeders/adminseed (interfaces: passwordHasher)
//
// Generated by this command:
//
//	mockgen -destination=mocks/seeder_mock.gen.go -package=adminseedmocks . passwordHasher
//

// Package adminseedmocks is a generated GoMock package.
package adminseedmocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockpasswordHasher is a mock of passwordHasher interface.
type MockpasswordHasher struct {
	ctrl     *gomock.Controller
	recorder *MockpasswordHasherMockRecorder
	isgomock struct{}
}

// MockpasswordHasherMockRecorder is the mock recorder for MockpasswordHasher.
type MockpasswordHasherMockRecorder struct {
	mock *MockpasswordHasher
}

// NewMockpasswordHasher creates a new mock instance.
func NewMockpasswordHasher(ctrl *gomock.Controller) *MockpasswordHasher {
	mock := &MockpasswordHasher{ctrl: ctrl}
	mock.recorder = &MockpasswordHasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpasswordHasher) EXPECT() *MockpasswordHasherMockRecorder {
	return m.recorder
}

// GenerateHash mocks base method.
func (m *MockpasswordHasher) GenerateHash(password string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateHash", password)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateHash indicates an expected call of GenerateHash.
func (mr *MockpasswordHasherMockRecorder) GenerateHash(password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateHash", reflect.TypeOf((*MockpasswordHasher)(nil).GenerateHash), password)
}
