// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/adminapp (interfaces: PermissionGuard,RolesService,OutboxPutter,UserRepo,SubjectEmailStore)
//
// Generated by this command:
//
//	mockgen -destination=mocks/app_mock.gen.go -package=adminappmocks . PermissionGuard,RolesService,OutboxPutter,UserRepo,SubjectEmailStore
//

// Package adminappmocks is a generated GoMock package.
package adminappmocks

import (
	context "context"
	reflect "reflect"
	time "time"

	goauth "github.com/assurrussa/goauth"
	fiber "github.com/gofiber/fiber/v3"
	gomock "go.uber.org/mock/gomock"

	datagrid "github.com/assurrussa/goadmin/infrastructure/core/datagrid"
	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
	auth "github.com/assurrussa/goadmin/internal/auth"
)

// MockPermissionGuard is a mock of PermissionGuard interface.
type MockPermissionGuard struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionGuardMockRecorder
	isgomock struct{}
}

// MockPermissionGuardMockRecorder is the mock recorder for MockPermissionGuard.
type MockPermissionGuardMockRecorder struct {
	mock *MockPermissionGuard
}

// NewMockPermissionGuard creates a new mock instance.
func NewMockPermissionGuard(ctrl *gomock.Controller) *MockPermissionGuard {
	mock := &MockPermissionGuard{ctrl: ctrl}
	mock.recorder = &MockPermissionGuardMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionGuard) EXPECT() *MockPermissionGuardMockRecorder {
	return m.recorder
}

// AdminGuard mocks base method.
func (m *MockPermissionGuard) AdminGuard(key auth.PermissionKey, opts ...auth.PermissionGuardOption) fiber.Handler {
	m.ctrl.T.Helper()
	varargs := []any{key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGuard", varargs...)
	ret0, _ := ret[0].(fiber.Handler)
	return ret0
}

// AdminGuard indicates an expected call of AdminGuard.
func (mr *MockPermissionGuardMockRecorder) AdminGuard(key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGuard", reflect.TypeOf((*MockPermissionGuard)(nil).AdminGuard), varargs...)
}

// MockRolesService is a mock of RolesService interface.
type MockRolesService struct {
	ctrl     *gomock.Controller
	recorder *MockRolesServiceMockRecorder
	isgomock struct{}
}

// MockRolesServiceMockRecorder is the mock recorder for MockRolesService.
type MockRolesServiceMockRecorder struct {
	mock *MockRolesService
}

// NewMockRolesService creates a new mock instance.
func NewMockRolesService(ctrl *gomock.Controller) *MockRolesService {
	mock := &MockRolesService{ctrl: ctrl}
	mock.recorder = &MockRolesServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRolesService) EXPECT() *MockRolesServiceMockRecorder {
	return m.recorder
}

// AdminCan mocks base method.
func (m *MockRolesService) AdminCan(ctx context.Context, adminID int64, domain auth.PermissionDomain, action auth.PermissionAction) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AdminCan", ctx, adminID, domain, action)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AdminCan indicates an expected call of AdminCan.
func (mr *MockRolesServiceMockRecorder) AdminCan(ctx, adminID, domain, action any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminCan", reflect.TypeOf((*MockRolesService)(nil).AdminCan), ctx, adminID, domain, action)
}

// AdminGuardCheck mocks base method.
func (m *MockRolesService) AdminGuardCheck(ctx context.Context, adminID int64, key auth.PermissionKey, opts ...auth.PermissionGuardOption) bool {
	m.ctrl.T.Helper()
	varargs := []any{ctx, adminID, key}
	for _, a := range opts {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "AdminGuardCheck", varargs...)
	ret0, _ := ret[0].(bool)
	return ret0
}

// AdminGuardCheck indicates an expected call of AdminGuardCheck.
func (mr *MockRolesServiceMockRecorder) AdminGuardCheck(ctx, adminID, key any, opts ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx, adminID, key}, opts...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AdminGuardCheck", reflect.TypeOf((*MockRolesService)(nil).AdminGuardCheck), varargs...)
}

// GetPermissions mocks base method.
func (m *MockRolesService) GetPermissions(ctx context.Context, roles []auth.Role) (map[int64]map[int64]auth.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPermissions", ctx, roles)
	ret0, _ := ret[0].(map[int64]map[int64]auth.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPermissions indicates an expected call of GetPermissions.
func (mr *MockRolesServiceMockRecorder) GetPermissions(ctx, roles any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPermissions", reflect.TypeOf((*MockRolesService)(nil).GetPermissions), ctx, roles)
}

// GetRolesAdmin mocks base method.
func (m *MockRolesService) GetRolesAdmin(ctx context.Context, adminID int64) ([]auth.Role, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRolesAdmin", ctx, adminID)
	ret0, _ := ret[0].([]auth.Role)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRolesAdmin indicates an expected call of GetRolesAdmin.
func (mr *MockRolesServiceMockRecorder) GetRolesAdmin(ctx, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRolesAdmin", reflect.TypeOf((*MockRolesService)(nil).GetRolesAdmin), ctx, adminID)
}

// IsAdoptedDetachRole mocks base method.
func (m *MockRolesService) IsAdoptedDetachRole(ctx context.Context, adminAuthID, adminID, roleID int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsAdoptedDetachRole", ctx, adminAuthID, adminID, roleID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsAdoptedDetachRole indicates an expected call of IsAdoptedDetachRole.
func (mr *MockRolesServiceMockRecorder) IsAdoptedDetachRole(ctx, adminAuthID, adminID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsAdoptedDetachRole", reflect.TypeOf((*MockRolesService)(nil).IsAdoptedDetachRole), ctx, adminAuthID, adminID, roleID)
}

// IsSuperAdmin mocks base method.
func (m *MockRolesService) IsSuperAdmin(ctx context.Context, adminID int64) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSuperAdmin", ctx, adminID)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsSuperAdmin indicates an expected call of IsSuperAdmin.
func (mr *MockRolesServiceMockRecorder) IsSuperAdmin(ctx, adminID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSuperAdmin", reflect.TypeOf((*MockRolesService)(nil).IsSuperAdmin), ctx, adminID)
}

// MockOutboxPutter is a mock of OutboxPutter interface.
type MockOutboxPutter struct {
	ctrl     *gomock.Controller
	recorder *MockOutboxPutterMockRecorder
	isgomock struct{}
}

// MockOutboxPutterMockRecorder is the mock recorder for MockOutboxPutter.
type MockOutboxPutterMockRecorder struct {
	mock *MockOutboxPutter
}

// NewMockOutboxPutter creates a new mock instance.
func NewMockOutboxPutter(ctrl *gomock.Controller) *MockOutboxPutter {
	mock := &MockOutboxPutter{ctrl: ctrl}
	mock.recorder = &MockOutboxPutterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOutboxPutter) EXPECT() *MockOutboxPutterMockRecorder {
	return m.recorder
}

// Put mocks base method.
func (m *MockOutboxPutter) Put(ctx context.Context, name, payload string, availableAt time.Time) (outbox.JobID, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Put", ctx, name, payload, availableAt)
	ret0, _ := ret[0].(outbox.JobID)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Put indicates an expected call of Put.
func (mr *MockOutboxPutterMockRecorder) Put(ctx, name, payload, availableAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Put", reflect.TypeOf((*MockOutboxPutter)(nil).Put), ctx, name, payload, availableAt)
}

// MockUserRepo is a mock of UserRepo interface.
type MockUserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockUserRepoMockRecorder
	isgomock struct{}
}

// MockUserRepoMockRecorder is the mock recorder for MockUserRepo.
type MockUserRepoMockRecorder struct {
	mock *MockUserRepo
}

// NewMockUserRepo creates a new mock instance.
func NewMockUserRepo(ctrl *gomock.Controller) *MockUserRepo {
	mock := &MockUserRepo{ctrl: ctrl}
	mock.recorder = &MockUserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRepo) EXPECT() *MockUserRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockUserRepo) GetByID(ctx context.Context, id int64) (auth.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(auth.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockUserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockUserRepo)(nil).GetByID), ctx, id)
}

// GetList mocks base method.
func (m *MockUserRepo) GetList(ctx context.Context, filters datagrid.Filtered) ([]auth.Profile, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filters)
	ret0, _ := ret[0].([]auth.Profile)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockUserRepoMockRecorder) GetList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockUserRepo)(nil).GetList), ctx, filters)
}

// RestoreByID mocks base method.
func (m *MockUserRepo) RestoreByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreByID indicates an expected call of RestoreByID.
func (mr *MockUserRepoMockRecorder) RestoreByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByID", reflect.TypeOf((*MockUserRepo)(nil).RestoreByID), ctx, id)
}

// SoftDeleteByID mocks base method.
func (m *MockUserRepo) SoftDeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByID indicates an expected call of SoftDeleteByID.
func (mr *MockUserRepoMockRecorder) SoftDeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByID", reflect.TypeOf((*MockUserRepo)(nil).SoftDeleteByID), ctx, id)
}

// Update mocks base method.
func (m *MockUserRepo) Update(ctx context.Context, id int64, user auth.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUserRepoMockRecorder) Update(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUserRepo)(nil).Update), ctx, id, user)
}

// MockSubjectEmailStore is a mock of SubjectEmailStore interface.
type MockSubjectEmailStore struct {
	ctrl     *gomock.Controller
	recorder *MockSubjectEmailStoreMockRecorder
	isgomock struct{}
}

// MockSubjectEmailStoreMockRecorder is the mock recorder for MockSubjectEmailStore.
type MockSubjectEmailStoreMockRecorder struct {
	mock *MockSubjectEmailStore
}

// NewMockSubjectEmailStore creates a new mock instance.
func NewMockSubjectEmailStore(ctrl *gomock.Controller) *MockSubjectEmailStore {
	mock := &MockSubjectEmailStore{ctrl: ctrl}
	mock.recorder = &MockSubjectEmailStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubjectEmailStore) EXPECT() *MockSubjectEmailStoreMockRecorder {
	return m.recorder
}

// RequestEmailChange mocks base method.
func (m *MockSubjectEmailStore) RequestEmailChange(ctx context.Context, subjectID goauth.SubjectID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailChange", ctx, subjectID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestEmailChange indicates an expected call of RequestEmailChange.
func (mr *MockSubjectEmailStoreMockRecorder) RequestEmailChange(ctx, subjectID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailChange", reflect.TypeOf((*MockSubjectEmailStore)(nil).RequestEmailChange), ctx, subjectID, newEmail)
}

// SetSubjectStatus mocks base method.
func (m *MockSubjectEmailStore) SetSubjectStatus(ctx context.Context, subjectID goauth.SubjectID, status goauth.SubjectStatus) (goauth.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubjectStatus", ctx, subjectID, status)
	ret0, _ := ret[0].(goauth.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSubjectStatus indicates an expected call of SetSubjectStatus.
func (mr *MockSubjectEmailStoreMockRecorder) SetSubjectStatus(ctx, subjectID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubjectStatus", reflect.TypeOf((*MockSubjectEmailStore)(nil).SetSubjectStatus), ctx, subjectID, status)
}

// UpdateBasicProfile mocks base method.
func (m *MockSubjectEmailStore) UpdateBasicProfile(ctx context.Context, subjectID goauth.SubjectID, profile goauth.BasicProfile) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicProfile", ctx, subjectID, profile)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicProfile indicates an expected call of UpdateBasicProfile.
func (mr *MockSubjectEmailStoreMockRecorder) UpdateBasicProfile(ctx, subjectID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicProfile", reflect.TypeOf((*MockSubjectEmailStore)(nil).UpdateBasicProfile), ctx, subjectID, profile)
}
