// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/http/handlers/administrations (interfaces: adminRepo,adminRoleNamesLister,adminAuthRuntime,fileRepo,previewService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.gen.go -package=administrationsmocks . adminRepo,adminRoleNamesLister,adminAuthRuntime,fileRepo,previewService
//

// Package administrationsmocks is a generated GoMock package.
package administrationsmocks

import (
	context "context"
	reflect "reflect"

	goauth "github.com/assurrussa/goauth"
	host "github.com/assurrussa/gouploads/host"
	gomock "go.uber.org/mock/gomock"

	datagrid "github.com/assurrussa/goadmin/infrastructure/core/datagrid"
	identity "github.com/assurrussa/goadmin/internal/identity"
	models "github.com/assurrussa/goadmin/models"
)

// MockadminRepo is a mock of adminRepo interface.
type MockadminRepo struct {
	ctrl     *gomock.Controller
	recorder *MockadminRepoMockRecorder
	isgomock struct{}
}

// MockadminRepoMockRecorder is the mock recorder for MockadminRepo.
type MockadminRepoMockRecorder struct {
	mock *MockadminRepo
}

// NewMockadminRepo creates a new mock instance.
func NewMockadminRepo(ctrl *gomock.Controller) *MockadminRepo {
	mock := &MockadminRepo{ctrl: ctrl}
	mock.recorder = &MockadminRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRepo) EXPECT() *MockadminRepoMockRecorder {
	return m.recorder
}

// DeleteByID mocks base method.
func (m *MockadminRepo) DeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockadminRepoMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockadminRepo)(nil).DeleteByID), ctx, id)
}

// GetByID mocks base method.
func (m *MockadminRepo) GetByID(ctx context.Context, id int64) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockadminRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockadminRepo)(nil).GetByID), ctx, id)
}

// GetByUUID mocks base method.
func (m *MockadminRepo) GetByUUID(ctx context.Context, id identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockadminRepoMockRecorder) GetByUUID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockadminRepo)(nil).GetByUUID), ctx, id)
}

// GetList mocks base method.
func (m *MockadminRepo) GetList(ctx context.Context, filters datagrid.Filtered) ([]models.Admin, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filters)
	ret0, _ := ret[0].([]models.Admin)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockadminRepoMockRecorder) GetList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockadminRepo)(nil).GetList), ctx, filters)
}

// ProvisionAccount mocks base method.
func (m *MockadminRepo) ProvisionAccount(ctx context.Context, account goauth.Account, publicID identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionAccount", ctx, account, publicID)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionAccount indicates an expected call of ProvisionAccount.
func (mr *MockadminRepoMockRecorder) ProvisionAccount(ctx, account, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionAccount", reflect.TypeOf((*MockadminRepo)(nil).ProvisionAccount), ctx, account, publicID)
}

// SoftDeleteByID mocks base method.
func (m *MockadminRepo) SoftDeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByID indicates an expected call of SoftDeleteByID.
func (mr *MockadminRepoMockRecorder) SoftDeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByID", reflect.TypeOf((*MockadminRepo)(nil).SoftDeleteByID), ctx, id)
}

// UpdateAdmin mocks base method.
func (m *MockadminRepo) UpdateAdmin(ctx context.Context, id int64, admin models.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdmin", ctx, id, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdmin indicates an expected call of UpdateAdmin.
func (mr *MockadminRepoMockRecorder) UpdateAdmin(ctx, id, admin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdmin", reflect.TypeOf((*MockadminRepo)(nil).UpdateAdmin), ctx, id, admin)
}

// MockadminRoleNamesLister is a mock of adminRoleNamesLister interface.
type MockadminRoleNamesLister struct {
	ctrl     *gomock.Controller
	recorder *MockadminRoleNamesListerMockRecorder
	isgomock struct{}
}

// MockadminRoleNamesListerMockRecorder is the mock recorder for MockadminRoleNamesLister.
type MockadminRoleNamesListerMockRecorder struct {
	mock *MockadminRoleNamesLister
}

// NewMockadminRoleNamesLister creates a new mock instance.
func NewMockadminRoleNamesLister(ctrl *gomock.Controller) *MockadminRoleNamesLister {
	mock := &MockadminRoleNamesLister{ctrl: ctrl}
	mock.recorder = &MockadminRoleNamesListerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRoleNamesLister) EXPECT() *MockadminRoleNamesListerMockRecorder {
	return m.recorder
}

// ListRoleNamesByAdminIDs mocks base method.
func (m *MockadminRoleNamesLister) ListRoleNamesByAdminIDs(ctx context.Context, adminIDs []int64) (map[int64][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoleNamesByAdminIDs", ctx, adminIDs)
	ret0, _ := ret[0].(map[int64][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoleNamesByAdminIDs indicates an expected call of ListRoleNamesByAdminIDs.
func (mr *MockadminRoleNamesListerMockRecorder) ListRoleNamesByAdminIDs(ctx, adminIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoleNamesByAdminIDs", reflect.TypeOf((*MockadminRoleNamesLister)(nil).ListRoleNamesByAdminIDs), ctx, adminIDs)
}

// MockadminAuthRuntime is a mock of adminAuthRuntime interface.
type MockadminAuthRuntime struct {
	ctrl     *gomock.Controller
	recorder *MockadminAuthRuntimeMockRecorder
	isgomock struct{}
}

// MockadminAuthRuntimeMockRecorder is the mock recorder for MockadminAuthRuntime.
type MockadminAuthRuntimeMockRecorder struct {
	mock *MockadminAuthRuntime
}

// NewMockadminAuthRuntime creates a new mock instance.
func NewMockadminAuthRuntime(ctrl *gomock.Controller) *MockadminAuthRuntime {
	mock := &MockadminAuthRuntime{ctrl: ctrl}
	mock.recorder = &MockadminAuthRuntimeMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminAuthRuntime) EXPECT() *MockadminAuthRuntimeMockRecorder {
	return m.recorder
}

// ProvisionTrustedAdmin mocks base method.
func (m *MockadminAuthRuntime) ProvisionTrustedAdmin(ctx context.Context, request goauth.RegisterRequest) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionTrustedAdmin", ctx, request)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionTrustedAdmin indicates an expected call of ProvisionTrustedAdmin.
func (mr *MockadminAuthRuntimeMockRecorder) ProvisionTrustedAdmin(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionTrustedAdmin", reflect.TypeOf((*MockadminAuthRuntime)(nil).ProvisionTrustedAdmin), ctx, request)
}

// RequestEmailChange mocks base method.
func (m *MockadminAuthRuntime) RequestEmailChange(ctx context.Context, subjectID goauth.SubjectID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailChange", ctx, subjectID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestEmailChange indicates an expected call of RequestEmailChange.
func (mr *MockadminAuthRuntimeMockRecorder) RequestEmailChange(ctx, subjectID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailChange", reflect.TypeOf((*MockadminAuthRuntime)(nil).RequestEmailChange), ctx, subjectID, newEmail)
}

// UpdateBasicProfile mocks base method.
func (m *MockadminAuthRuntime) UpdateBasicProfile(ctx context.Context, subjectID goauth.SubjectID, profile goauth.BasicProfile) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicProfile", ctx, subjectID, profile)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicProfile indicates an expected call of UpdateBasicProfile.
func (mr *MockadminAuthRuntimeMockRecorder) UpdateBasicProfile(ctx, subjectID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicProfile", reflect.TypeOf((*MockadminAuthRuntime)(nil).UpdateBasicProfile), ctx, subjectID, profile)
}

// MockfileRepo is a mock of fileRepo interface.
type MockfileRepo struct {
	ctrl     *gomock.Controller
	recorder *MockfileRepoMockRecorder
	isgomock struct{}
}

// MockfileRepoMockRecorder is the mock recorder for MockfileRepo.
type MockfileRepoMockRecorder struct {
	mock *MockfileRepo
}

// NewMockfileRepo creates a new mock instance.
func NewMockfileRepo(ctrl *gomock.Controller) *MockfileRepo {
	mock := &MockfileRepo{ctrl: ctrl}
	mock.recorder = &MockfileRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileRepo) EXPECT() *MockfileRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockfileRepo) GetByID(ctx context.Context, id int64) (host.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(host.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockfileRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockfileRepo)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockfileRepo) Update(ctx context.Context, id int64, file host.File) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, file)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockfileRepoMockRecorder) Update(ctx, id, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockfileRepo)(nil).Update), ctx, id, file)
}

// MockpreviewService is a mock of previewService interface.
type MockpreviewService struct {
	ctrl     *gomock.Controller
	recorder *MockpreviewServiceMockRecorder
	isgomock struct{}
}

// MockpreviewServiceMockRecorder is the mock recorder for MockpreviewService.
type MockpreviewServiceMockRecorder struct {
	mock *MockpreviewService
}

// NewMockpreviewService creates a new mock instance.
func NewMockpreviewService(ctrl *gomock.Controller) *MockpreviewService {
	mock := &MockpreviewService{ctrl: ctrl}
	mock.recorder = &MockpreviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpreviewService) EXPECT() *MockpreviewServiceMockRecorder {
	return m.recorder
}

// LoadPreview mocks base method.
func (m *MockpreviewService) LoadPreview(ctx context.Context, fileID int64) (*host.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPreview", ctx, fileID)
	ret0, _ := ret[0].(*host.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPreview indicates an expected call of LoadPreview.
func (mr *MockpreviewServiceMockRecorder) LoadPreview(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPreview", reflect.TypeOf((*MockpreviewService)(nil).LoadPreview), ctx, fileID)
}
