// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/http/handlers/auth (interfaces: adminRepo,previewService,sessionStoreActions,adminAccountService,adminLoginAuditWriter,firstAdminSetupTokens)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.gen.go -package=authmocks . adminRepo,previewService,sessionStoreActions,adminAccountService,adminLoginAuditWriter,firstAdminSetupTokens
//

// Package authmocks is a generated GoMock package.
package authmocks

import (
	context "context"
	reflect "reflect"

	goauth "github.com/assurrussa/goauth"
	host "github.com/assurrussa/gouploads/host"
	fiber "github.com/gofiber/fiber/v3"
	gomock "go.uber.org/mock/gomock"

	auth "github.com/assurrussa/goadmin/internal/auth"
	identity "github.com/assurrussa/goadmin/internal/identity"
	loginaudit "github.com/assurrussa/goadmin/loginaudit"
	models "github.com/assurrussa/goadmin/models"
)

// MockadminRepo is a mock of adminRepo interface.
type MockadminRepo struct {
	ctrl     *gomock.Controller
	recorder *MockadminRepoMockRecorder
	isgomock struct{}
}

// MockadminRepoMockRecorder is the mock recorder for MockadminRepo.
type MockadminRepoMockRecorder struct {
	mock *MockadminRepo
}

// NewMockadminRepo creates a new mock instance.
func NewMockadminRepo(ctrl *gomock.Controller) *MockadminRepo {
	mock := &MockadminRepo{ctrl: ctrl}
	mock.recorder = &MockadminRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRepo) EXPECT() *MockadminRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockadminRepo) GetByID(ctx context.Context, id int64) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockadminRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockadminRepo)(nil).GetByID), ctx, id)
}

// GetByUUID mocks base method.
func (m *MockadminRepo) GetByUUID(ctx context.Context, id identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockadminRepoMockRecorder) GetByUUID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockadminRepo)(nil).GetByUUID), ctx, id)
}

// ProvisionAccount mocks base method.
func (m *MockadminRepo) ProvisionAccount(ctx context.Context, account goauth.Account, publicID identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionAccount", ctx, account, publicID)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionAccount indicates an expected call of ProvisionAccount.
func (mr *MockadminRepoMockRecorder) ProvisionAccount(ctx, account, publicID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionAccount", reflect.TypeOf((*MockadminRepo)(nil).ProvisionAccount), ctx, account, publicID)
}

// UpdateAdmin mocks base method.
func (m *MockadminRepo) UpdateAdmin(ctx context.Context, id int64, admin models.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdmin", ctx, id, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdmin indicates an expected call of UpdateAdmin.
func (mr *MockadminRepoMockRecorder) UpdateAdmin(ctx, id, admin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdmin", reflect.TypeOf((*MockadminRepo)(nil).UpdateAdmin), ctx, id, admin)
}

// MockpreviewService is a mock of previewService interface.
type MockpreviewService struct {
	ctrl     *gomock.Controller
	recorder *MockpreviewServiceMockRecorder
	isgomock struct{}
}

// MockpreviewServiceMockRecorder is the mock recorder for MockpreviewService.
type MockpreviewServiceMockRecorder struct {
	mock *MockpreviewService
}

// NewMockpreviewService creates a new mock instance.
func NewMockpreviewService(ctrl *gomock.Controller) *MockpreviewService {
	mock := &MockpreviewService{ctrl: ctrl}
	mock.recorder = &MockpreviewServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpreviewService) EXPECT() *MockpreviewServiceMockRecorder {
	return m.recorder
}

// LoadPreview mocks base method.
func (m *MockpreviewService) LoadPreview(ctx context.Context, fileID int64) (*host.File, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadPreview", ctx, fileID)
	ret0, _ := ret[0].(*host.File)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LoadPreview indicates an expected call of LoadPreview.
func (mr *MockpreviewServiceMockRecorder) LoadPreview(ctx, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadPreview", reflect.TypeOf((*MockpreviewService)(nil).LoadPreview), ctx, fileID)
}

// MocksessionStoreActions is a mock of sessionStoreActions interface.
type MocksessionStoreActions struct {
	ctrl     *gomock.Controller
	recorder *MocksessionStoreActionsMockRecorder
	isgomock struct{}
}

// MocksessionStoreActionsMockRecorder is the mock recorder for MocksessionStoreActions.
type MocksessionStoreActionsMockRecorder struct {
	mock *MocksessionStoreActions
}

// NewMocksessionStoreActions creates a new mock instance.
func NewMocksessionStoreActions(ctrl *gomock.Controller) *MocksessionStoreActions {
	mock := &MocksessionStoreActions{ctrl: ctrl}
	mock.recorder = &MocksessionStoreActionsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionStoreActions) EXPECT() *MocksessionStoreActionsMockRecorder {
	return m.recorder
}

// ApplyCookiePolicy mocks base method.
func (m *MocksessionStoreActions) ApplyCookiePolicy(c fiber.Ctx, persistent bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ApplyCookiePolicy", c, persistent)
	ret0, _ := ret[0].(error)
	return ret0
}

// ApplyCookiePolicy indicates an expected call of ApplyCookiePolicy.
func (mr *MocksessionStoreActionsMockRecorder) ApplyCookiePolicy(c, persistent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ApplyCookiePolicy", reflect.TypeOf((*MocksessionStoreActions)(nil).ApplyCookiePolicy), c, persistent)
}

// DelAdminAuth mocks base method.
func (m *MocksessionStoreActions) DelAdminAuth(c fiber.Ctx) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelAdminAuth", c)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelAdminAuth indicates an expected call of DelAdminAuth.
func (mr *MocksessionStoreActionsMockRecorder) DelAdminAuth(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelAdminAuth", reflect.TypeOf((*MocksessionStoreActions)(nil).DelAdminAuth), c)
}

// DeleteAll mocks base method.
func (m *MocksessionStoreActions) DeleteAll(ctx context.Context, subjectID auth.SubjectID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAll", ctx, subjectID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAll indicates an expected call of DeleteAll.
func (mr *MocksessionStoreActionsMockRecorder) DeleteAll(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAll", reflect.TypeOf((*MocksessionStoreActions)(nil).DeleteAll), ctx, subjectID)
}

// DeleteAllExcept mocks base method.
func (m *MocksessionStoreActions) DeleteAllExcept(ctx context.Context, subjectID auth.SubjectID, keepToken string) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllExcept", ctx, subjectID, keepToken)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeleteAllExcept indicates an expected call of DeleteAllExcept.
func (mr *MocksessionStoreActionsMockRecorder) DeleteAllExcept(ctx, subjectID, keepToken any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllExcept", reflect.TypeOf((*MocksessionStoreActions)(nil).DeleteAllExcept), ctx, subjectID, keepToken)
}

// LoginAdmin mocks base method.
func (m *MocksessionStoreActions) LoginAdmin(c fiber.Ctx, email, password string, persistent bool) (models.Admin, goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoginAdmin", c, email, password, persistent)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(goauth.Account)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// LoginAdmin indicates an expected call of LoginAdmin.
func (mr *MocksessionStoreActionsMockRecorder) LoginAdmin(c, email, password, persistent any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoginAdmin", reflect.TypeOf((*MocksessionStoreActions)(nil).LoginAdmin), c, email, password, persistent)
}

// ProvisionTrustedAdmin mocks base method.
func (m *MocksessionStoreActions) ProvisionTrustedAdmin(ctx context.Context, request goauth.RegisterRequest) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProvisionTrustedAdmin", ctx, request)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ProvisionTrustedAdmin indicates an expected call of ProvisionTrustedAdmin.
func (mr *MocksessionStoreActionsMockRecorder) ProvisionTrustedAdmin(ctx, request any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProvisionTrustedAdmin", reflect.TypeOf((*MocksessionStoreActions)(nil).ProvisionTrustedAdmin), ctx, request)
}

// RotateAdminAuth mocks base method.
func (m *MocksessionStoreActions) RotateAdminAuth(c fiber.Ctx, user models.Admin) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RotateAdminAuth", c, user)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RotateAdminAuth indicates an expected call of RotateAdminAuth.
func (mr *MocksessionStoreActionsMockRecorder) RotateAdminAuth(c, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RotateAdminAuth", reflect.TypeOf((*MocksessionStoreActions)(nil).RotateAdminAuth), c, user)
}

// MockadminAccountService is a mock of adminAccountService interface.
type MockadminAccountService struct {
	ctrl     *gomock.Controller
	recorder *MockadminAccountServiceMockRecorder
	isgomock struct{}
}

// MockadminAccountServiceMockRecorder is the mock recorder for MockadminAccountService.
type MockadminAccountServiceMockRecorder struct {
	mock *MockadminAccountService
}

// NewMockadminAccountService creates a new mock instance.
func NewMockadminAccountService(ctrl *gomock.Controller) *MockadminAccountService {
	mock := &MockadminAccountService{ctrl: ctrl}
	mock.recorder = &MockadminAccountServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminAccountService) EXPECT() *MockadminAccountServiceMockRecorder {
	return m.recorder
}

// ChangePassword mocks base method.
func (m *MockadminAccountService) ChangePassword(ctx context.Context, subjectID auth.SubjectID, currentPassword, newPassword string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ChangePassword", ctx, subjectID, currentPassword, newPassword)
	ret0, _ := ret[0].(error)
	return ret0
}

// ChangePassword indicates an expected call of ChangePassword.
func (mr *MockadminAccountServiceMockRecorder) ChangePassword(ctx, subjectID, currentPassword, newPassword any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ChangePassword", reflect.TypeOf((*MockadminAccountService)(nil).ChangePassword), ctx, subjectID, currentPassword, newPassword)
}

// ConfirmEmailChange mocks base method.
func (m *MockadminAccountService) ConfirmEmailChange(ctx context.Context, subjectID auth.SubjectID, code string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConfirmEmailChange", ctx, subjectID, code)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConfirmEmailChange indicates an expected call of ConfirmEmailChange.
func (mr *MockadminAccountServiceMockRecorder) ConfirmEmailChange(ctx, subjectID, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConfirmEmailChange", reflect.TypeOf((*MockadminAccountService)(nil).ConfirmEmailChange), ctx, subjectID, code)
}

// GetPendingEmailChange mocks base method.
func (m *MockadminAccountService) GetPendingEmailChange(ctx context.Context, subjectID auth.SubjectID) (*goauth.PendingEmailChange, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPendingEmailChange", ctx, subjectID)
	ret0, _ := ret[0].(*goauth.PendingEmailChange)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPendingEmailChange indicates an expected call of GetPendingEmailChange.
func (mr *MockadminAccountServiceMockRecorder) GetPendingEmailChange(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPendingEmailChange", reflect.TypeOf((*MockadminAccountService)(nil).GetPendingEmailChange), ctx, subjectID)
}

// PerformPasswordReset mocks base method.
func (m *MockadminAccountService) PerformPasswordReset(ctx context.Context, token, password string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PerformPasswordReset", ctx, token, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// PerformPasswordReset indicates an expected call of PerformPasswordReset.
func (mr *MockadminAccountServiceMockRecorder) PerformPasswordReset(ctx, token, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PerformPasswordReset", reflect.TypeOf((*MockadminAccountService)(nil).PerformPasswordReset), ctx, token, password)
}

// RequestEmailChangeWithPassword mocks base method.
func (m *MockadminAccountService) RequestEmailChangeWithPassword(ctx context.Context, subjectID auth.SubjectID, currentPassword, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailChangeWithPassword", ctx, subjectID, currentPassword, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestEmailChangeWithPassword indicates an expected call of RequestEmailChangeWithPassword.
func (mr *MockadminAccountServiceMockRecorder) RequestEmailChangeWithPassword(ctx, subjectID, currentPassword, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailChangeWithPassword", reflect.TypeOf((*MockadminAccountService)(nil).RequestEmailChangeWithPassword), ctx, subjectID, currentPassword, newEmail)
}

// RequestPasswordReset mocks base method.
func (m *MockadminAccountService) RequestPasswordReset(ctx context.Context, email string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestPasswordReset", ctx, email)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestPasswordReset indicates an expected call of RequestPasswordReset.
func (mr *MockadminAccountServiceMockRecorder) RequestPasswordReset(ctx, email any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestPasswordReset", reflect.TypeOf((*MockadminAccountService)(nil).RequestPasswordReset), ctx, email)
}

// UpdateBasicProfile mocks base method.
func (m *MockadminAccountService) UpdateBasicProfile(ctx context.Context, subjectID goauth.SubjectID, profile goauth.BasicProfile) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicProfile", ctx, subjectID, profile)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicProfile indicates an expected call of UpdateBasicProfile.
func (mr *MockadminAccountServiceMockRecorder) UpdateBasicProfile(ctx, subjectID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicProfile", reflect.TypeOf((*MockadminAccountService)(nil).UpdateBasicProfile), ctx, subjectID, profile)
}

// MockadminLoginAuditWriter is a mock of adminLoginAuditWriter interface.
type MockadminLoginAuditWriter struct {
	ctrl     *gomock.Controller
	recorder *MockadminLoginAuditWriterMockRecorder
	isgomock struct{}
}

// MockadminLoginAuditWriterMockRecorder is the mock recorder for MockadminLoginAuditWriter.
type MockadminLoginAuditWriterMockRecorder struct {
	mock *MockadminLoginAuditWriter
}

// NewMockadminLoginAuditWriter creates a new mock instance.
func NewMockadminLoginAuditWriter(ctrl *gomock.Controller) *MockadminLoginAuditWriter {
	mock := &MockadminLoginAuditWriter{ctrl: ctrl}
	mock.recorder = &MockadminLoginAuditWriterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminLoginAuditWriter) EXPECT() *MockadminLoginAuditWriterMockRecorder {
	return m.recorder
}

// RecordSuccessfulLogin mocks base method.
func (m *MockadminLoginAuditWriter) RecordSuccessfulLogin(ctx context.Context, record loginaudit.Record) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecordSuccessfulLogin", ctx, record)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecordSuccessfulLogin indicates an expected call of RecordSuccessfulLogin.
func (mr *MockadminLoginAuditWriterMockRecorder) RecordSuccessfulLogin(ctx, record any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecordSuccessfulLogin", reflect.TypeOf((*MockadminLoginAuditWriter)(nil).RecordSuccessfulLogin), ctx, record)
}

// MockfirstAdminSetupTokens is a mock of firstAdminSetupTokens interface.
type MockfirstAdminSetupTokens struct {
	ctrl     *gomock.Controller
	recorder *MockfirstAdminSetupTokensMockRecorder
	isgomock struct{}
}

// MockfirstAdminSetupTokensMockRecorder is the mock recorder for MockfirstAdminSetupTokens.
type MockfirstAdminSetupTokensMockRecorder struct {
	mock *MockfirstAdminSetupTokens
}

// NewMockfirstAdminSetupTokens creates a new mock instance.
func NewMockfirstAdminSetupTokens(ctrl *gomock.Controller) *MockfirstAdminSetupTokens {
	mock := &MockfirstAdminSetupTokens{ctrl: ctrl}
	mock.recorder = &MockfirstAdminSetupTokensMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfirstAdminSetupTokens) EXPECT() *MockfirstAdminSetupTokensMockRecorder {
	return m.recorder
}

// Consume mocks base method.
func (m *MockfirstAdminSetupTokens) Consume(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Consume", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Consume indicates an expected call of Consume.
func (mr *MockfirstAdminSetupTokensMockRecorder) Consume(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Consume", reflect.TypeOf((*MockfirstAdminSetupTokens)(nil).Consume), ctx, token)
}

// StaticConfigured mocks base method.
func (m *MockfirstAdminSetupTokens) StaticConfigured() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StaticConfigured")
	ret0, _ := ret[0].(bool)
	return ret0
}

// StaticConfigured indicates an expected call of StaticConfigured.
func (mr *MockfirstAdminSetupTokensMockRecorder) StaticConfigured() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StaticConfigured", reflect.TypeOf((*MockfirstAdminSetupTokens)(nil).StaticConfigured))
}

// Validate mocks base method.
func (m *MockfirstAdminSetupTokens) Validate(ctx context.Context, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Validate", ctx, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// Validate indicates an expected call of Validate.
func (mr *MockfirstAdminSetupTokensMockRecorder) Validate(ctx, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Validate", reflect.TypeOf((*MockfirstAdminSetupTokens)(nil).Validate), ctx, token)
}
