// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/http/handlers/roles (interfaces: listRolesUseCase,getRoleUseCase,createRoleUseCase,updateRoleUseCase,deleteRoleUseCase,setPermissionsUseCase,assignAdminRolesUseCase,adminRoleTransaction,listPermissionsUseCase,listRolePermissionsUseCase,listAdminRolesUseCase,listAllRolesUseCase,adminRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.gen.go -package=rolesmocks . listRolesUseCase,getRoleUseCase,createRoleUseCase,updateRoleUseCase,deleteRoleUseCase,setPermissionsUseCase,assignAdminRolesUseCase,adminRoleTransaction,listPermissionsUseCase,listRolePermissionsUseCase,listAdminRolesUseCase,listAllRolesUseCase,adminRepository
//

// Package rolesmocks is a generated GoMock package.
package rolesmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	roles "github.com/assurrussa/goadmin/http/handlers/roles"
	datagrid "github.com/assurrussa/goadmin/infrastructure/core/datagrid"
	auth "github.com/assurrussa/goadmin/internal/auth"
	identity "github.com/assurrussa/goadmin/internal/identity"
	models "github.com/assurrussa/goadmin/models"
)

// MocklistRolesUseCase is a mock of listRolesUseCase interface.
type MocklistRolesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistRolesUseCaseMockRecorder
	isgomock struct{}
}

// MocklistRolesUseCaseMockRecorder is the mock recorder for MocklistRolesUseCase.
type MocklistRolesUseCaseMockRecorder struct {
	mock *MocklistRolesUseCase
}

// NewMocklistRolesUseCase creates a new mock instance.
func NewMocklistRolesUseCase(ctrl *gomock.Controller) *MocklistRolesUseCase {
	mock := &MocklistRolesUseCase{ctrl: ctrl}
	mock.recorder = &MocklistRolesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistRolesUseCase) EXPECT() *MocklistRolesUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistRolesUseCase) Handle(ctx context.Context, req auth.ListRolesRequest) (auth.ListRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.ListRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistRolesUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistRolesUseCase)(nil).Handle), ctx, req)
}

// MockgetRoleUseCase is a mock of getRoleUseCase interface.
type MockgetRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockgetRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockgetRoleUseCaseMockRecorder is the mock recorder for MockgetRoleUseCase.
type MockgetRoleUseCaseMockRecorder struct {
	mock *MockgetRoleUseCase
}

// NewMockgetRoleUseCase creates a new mock instance.
func NewMockgetRoleUseCase(ctrl *gomock.Controller) *MockgetRoleUseCase {
	mock := &MockgetRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockgetRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgetRoleUseCase) EXPECT() *MockgetRoleUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockgetRoleUseCase) Handle(ctx context.Context, req auth.GetRoleRequest) (auth.GetRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.GetRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockgetRoleUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockgetRoleUseCase)(nil).Handle), ctx, req)
}

// MockcreateRoleUseCase is a mock of createRoleUseCase interface.
type MockcreateRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockcreateRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockcreateRoleUseCaseMockRecorder is the mock recorder for MockcreateRoleUseCase.
type MockcreateRoleUseCaseMockRecorder struct {
	mock *MockcreateRoleUseCase
}

// NewMockcreateRoleUseCase creates a new mock instance.
func NewMockcreateRoleUseCase(ctrl *gomock.Controller) *MockcreateRoleUseCase {
	mock := &MockcreateRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockcreateRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcreateRoleUseCase) EXPECT() *MockcreateRoleUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockcreateRoleUseCase) Handle(ctx context.Context, req auth.CreateRoleRequest) (auth.CreateRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.CreateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockcreateRoleUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockcreateRoleUseCase)(nil).Handle), ctx, req)
}

// MockupdateRoleUseCase is a mock of updateRoleUseCase interface.
type MockupdateRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockupdateRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockupdateRoleUseCaseMockRecorder is the mock recorder for MockupdateRoleUseCase.
type MockupdateRoleUseCaseMockRecorder struct {
	mock *MockupdateRoleUseCase
}

// NewMockupdateRoleUseCase creates a new mock instance.
func NewMockupdateRoleUseCase(ctrl *gomock.Controller) *MockupdateRoleUseCase {
	mock := &MockupdateRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockupdateRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockupdateRoleUseCase) EXPECT() *MockupdateRoleUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockupdateRoleUseCase) Handle(ctx context.Context, req auth.UpdateRoleRequest) (auth.UpdateRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.UpdateRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockupdateRoleUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockupdateRoleUseCase)(nil).Handle), ctx, req)
}

// MockdeleteRoleUseCase is a mock of deleteRoleUseCase interface.
type MockdeleteRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockdeleteRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockdeleteRoleUseCaseMockRecorder is the mock recorder for MockdeleteRoleUseCase.
type MockdeleteRoleUseCaseMockRecorder struct {
	mock *MockdeleteRoleUseCase
}

// NewMockdeleteRoleUseCase creates a new mock instance.
func NewMockdeleteRoleUseCase(ctrl *gomock.Controller) *MockdeleteRoleUseCase {
	mock := &MockdeleteRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockdeleteRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockdeleteRoleUseCase) EXPECT() *MockdeleteRoleUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockdeleteRoleUseCase) Handle(ctx context.Context, req auth.DeleteRoleRequest) (auth.DeleteRoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.DeleteRoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockdeleteRoleUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockdeleteRoleUseCase)(nil).Handle), ctx, req)
}

// MocksetPermissionsUseCase is a mock of setPermissionsUseCase interface.
type MocksetPermissionsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocksetPermissionsUseCaseMockRecorder
	isgomock struct{}
}

// MocksetPermissionsUseCaseMockRecorder is the mock recorder for MocksetPermissionsUseCase.
type MocksetPermissionsUseCaseMockRecorder struct {
	mock *MocksetPermissionsUseCase
}

// NewMocksetPermissionsUseCase creates a new mock instance.
func NewMocksetPermissionsUseCase(ctrl *gomock.Controller) *MocksetPermissionsUseCase {
	mock := &MocksetPermissionsUseCase{ctrl: ctrl}
	mock.recorder = &MocksetPermissionsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksetPermissionsUseCase) EXPECT() *MocksetPermissionsUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocksetPermissionsUseCase) Handle(ctx context.Context, req auth.SetRolePermissionsRequest) (auth.SetRolePermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.SetRolePermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocksetPermissionsUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocksetPermissionsUseCase)(nil).Handle), ctx, req)
}

// MockassignAdminRolesUseCase is a mock of assignAdminRolesUseCase interface.
type MockassignAdminRolesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockassignAdminRolesUseCaseMockRecorder
	isgomock struct{}
}

// MockassignAdminRolesUseCaseMockRecorder is the mock recorder for MockassignAdminRolesUseCase.
type MockassignAdminRolesUseCaseMockRecorder struct {
	mock *MockassignAdminRolesUseCase
}

// NewMockassignAdminRolesUseCase creates a new mock instance.
func NewMockassignAdminRolesUseCase(ctrl *gomock.Controller) *MockassignAdminRolesUseCase {
	mock := &MockassignAdminRolesUseCase{ctrl: ctrl}
	mock.recorder = &MockassignAdminRolesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockassignAdminRolesUseCase) EXPECT() *MockassignAdminRolesUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MockassignAdminRolesUseCase) Handle(ctx context.Context, req roles.AssignAdminRolesRequest) (roles.AssignAdminRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(roles.AssignAdminRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MockassignAdminRolesUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MockassignAdminRolesUseCase)(nil).Handle), ctx, req)
}

// MockadminRoleTransaction is a mock of adminRoleTransaction interface.
type MockadminRoleTransaction struct {
	ctrl     *gomock.Controller
	recorder *MockadminRoleTransactionMockRecorder
	isgomock struct{}
}

// MockadminRoleTransactionMockRecorder is the mock recorder for MockadminRoleTransaction.
type MockadminRoleTransactionMockRecorder struct {
	mock *MockadminRoleTransaction
}

// NewMockadminRoleTransaction creates a new mock instance.
func NewMockadminRoleTransaction(ctrl *gomock.Controller) *MockadminRoleTransaction {
	mock := &MockadminRoleTransaction{ctrl: ctrl}
	mock.recorder = &MockadminRoleTransactionMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRoleTransaction) EXPECT() *MockadminRoleTransactionMockRecorder {
	return m.recorder
}

// InAdminRoleTransaction mocks base method.
func (m *MockadminRoleTransaction) InAdminRoleTransaction(ctx context.Context, actorID, adminID int64, fn func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InAdminRoleTransaction", ctx, actorID, adminID, fn)
	ret0, _ := ret[0].(error)
	return ret0
}

// InAdminRoleTransaction indicates an expected call of InAdminRoleTransaction.
func (mr *MockadminRoleTransactionMockRecorder) InAdminRoleTransaction(ctx, actorID, adminID, fn any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InAdminRoleTransaction", reflect.TypeOf((*MockadminRoleTransaction)(nil).InAdminRoleTransaction), ctx, actorID, adminID, fn)
}

// MocklistPermissionsUseCase is a mock of listPermissionsUseCase interface.
type MocklistPermissionsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistPermissionsUseCaseMockRecorder
	isgomock struct{}
}

// MocklistPermissionsUseCaseMockRecorder is the mock recorder for MocklistPermissionsUseCase.
type MocklistPermissionsUseCaseMockRecorder struct {
	mock *MocklistPermissionsUseCase
}

// NewMocklistPermissionsUseCase creates a new mock instance.
func NewMocklistPermissionsUseCase(ctrl *gomock.Controller) *MocklistPermissionsUseCase {
	mock := &MocklistPermissionsUseCase{ctrl: ctrl}
	mock.recorder = &MocklistPermissionsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistPermissionsUseCase) EXPECT() *MocklistPermissionsUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistPermissionsUseCase) Handle(ctx context.Context, req auth.ListPermissionsRequest) (auth.ListPermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.ListPermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistPermissionsUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistPermissionsUseCase)(nil).Handle), ctx, req)
}

// MocklistRolePermissionsUseCase is a mock of listRolePermissionsUseCase interface.
type MocklistRolePermissionsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistRolePermissionsUseCaseMockRecorder
	isgomock struct{}
}

// MocklistRolePermissionsUseCaseMockRecorder is the mock recorder for MocklistRolePermissionsUseCase.
type MocklistRolePermissionsUseCaseMockRecorder struct {
	mock *MocklistRolePermissionsUseCase
}

// NewMocklistRolePermissionsUseCase creates a new mock instance.
func NewMocklistRolePermissionsUseCase(ctrl *gomock.Controller) *MocklistRolePermissionsUseCase {
	mock := &MocklistRolePermissionsUseCase{ctrl: ctrl}
	mock.recorder = &MocklistRolePermissionsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistRolePermissionsUseCase) EXPECT() *MocklistRolePermissionsUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistRolePermissionsUseCase) Handle(ctx context.Context, req auth.ListRolePermissionsRequest) (auth.ListRolePermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.ListRolePermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistRolePermissionsUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistRolePermissionsUseCase)(nil).Handle), ctx, req)
}

// MocklistAdminRolesUseCase is a mock of listAdminRolesUseCase interface.
type MocklistAdminRolesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistAdminRolesUseCaseMockRecorder
	isgomock struct{}
}

// MocklistAdminRolesUseCaseMockRecorder is the mock recorder for MocklistAdminRolesUseCase.
type MocklistAdminRolesUseCaseMockRecorder struct {
	mock *MocklistAdminRolesUseCase
}

// NewMocklistAdminRolesUseCase creates a new mock instance.
func NewMocklistAdminRolesUseCase(ctrl *gomock.Controller) *MocklistAdminRolesUseCase {
	mock := &MocklistAdminRolesUseCase{ctrl: ctrl}
	mock.recorder = &MocklistAdminRolesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistAdminRolesUseCase) EXPECT() *MocklistAdminRolesUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistAdminRolesUseCase) Handle(ctx context.Context, req roles.ListAdminRolesRequest) (roles.ListAdminRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(roles.ListAdminRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistAdminRolesUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistAdminRolesUseCase)(nil).Handle), ctx, req)
}

// MocklistAllRolesUseCase is a mock of listAllRolesUseCase interface.
type MocklistAllRolesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistAllRolesUseCaseMockRecorder
	isgomock struct{}
}

// MocklistAllRolesUseCaseMockRecorder is the mock recorder for MocklistAllRolesUseCase.
type MocklistAllRolesUseCaseMockRecorder struct {
	mock *MocklistAllRolesUseCase
}

// NewMocklistAllRolesUseCase creates a new mock instance.
func NewMocklistAllRolesUseCase(ctrl *gomock.Controller) *MocklistAllRolesUseCase {
	mock := &MocklistAllRolesUseCase{ctrl: ctrl}
	mock.recorder = &MocklistAllRolesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistAllRolesUseCase) EXPECT() *MocklistAllRolesUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistAllRolesUseCase) Handle(ctx context.Context, req auth.ListAllRolesRequest) (auth.ListAllRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.ListAllRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistAllRolesUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistAllRolesUseCase)(nil).Handle), ctx, req)
}

// MockadminRepository is a mock of adminRepository interface.
type MockadminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockadminRepositoryMockRecorder
	isgomock struct{}
}

// MockadminRepositoryMockRecorder is the mock recorder for MockadminRepository.
type MockadminRepositoryMockRecorder struct {
	mock *MockadminRepository
}

// NewMockadminRepository creates a new mock instance.
func NewMockadminRepository(ctrl *gomock.Controller) *MockadminRepository {
	mock := &MockadminRepository{ctrl: ctrl}
	mock.recorder = &MockadminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRepository) EXPECT() *MockadminRepositoryMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockadminRepository) GetByID(ctx context.Context, id int64) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockadminRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockadminRepository)(nil).GetByID), ctx, id)
}

// GetBySubjectID mocks base method.
func (m *MockadminRepository) GetBySubjectID(ctx context.Context, subjectID auth.SubjectID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySubjectID", ctx, subjectID)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySubjectID indicates an expected call of GetBySubjectID.
func (mr *MockadminRepositoryMockRecorder) GetBySubjectID(ctx, subjectID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySubjectID", reflect.TypeOf((*MockadminRepository)(nil).GetBySubjectID), ctx, subjectID)
}

// GetByUUID mocks base method.
func (m *MockadminRepository) GetByUUID(ctx context.Context, id identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockadminRepositoryMockRecorder) GetByUUID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockadminRepository)(nil).GetByUUID), ctx, id)
}

// GetList mocks base method.
func (m *MockadminRepository) GetList(ctx context.Context, filters datagrid.Filtered) ([]models.Admin, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filters)
	ret0, _ := ret[0].([]models.Admin)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockadminRepositoryMockRecorder) GetList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockadminRepository)(nil).GetList), ctx, filters)
}
