// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/handler_mock.gen.go -package=usersmocks
//

// Package usersmocks is a generated GoMock package.
package usersmocks

import (
	context "context"
	reflect "reflect"

	goauth "github.com/assurrussa/goauth"
	gomock "go.uber.org/mock/gomock"

	datagrid "github.com/assurrussa/goadmin/infrastructure/core/datagrid"
	auth "github.com/assurrussa/goadmin/internal/auth"
)

// MockuserRepo is a mock of userRepo interface.
type MockuserRepo struct {
	ctrl     *gomock.Controller
	recorder *MockuserRepoMockRecorder
	isgomock struct{}
}

// MockuserRepoMockRecorder is the mock recorder for MockuserRepo.
type MockuserRepoMockRecorder struct {
	mock *MockuserRepo
}

// NewMockuserRepo creates a new mock instance.
func NewMockuserRepo(ctrl *gomock.Controller) *MockuserRepo {
	mock := &MockuserRepo{ctrl: ctrl}
	mock.recorder = &MockuserRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserRepo) EXPECT() *MockuserRepoMockRecorder {
	return m.recorder
}

// GetByID mocks base method.
func (m *MockuserRepo) GetByID(ctx context.Context, id int64) (auth.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(auth.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserRepo)(nil).GetByID), ctx, id)
}

// GetList mocks base method.
func (m *MockuserRepo) GetList(ctx context.Context, filters datagrid.Filtered) ([]auth.Profile, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx, filters)
	ret0, _ := ret[0].([]auth.Profile)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GetList indicates an expected call of GetList.
func (mr *MockuserRepoMockRecorder) GetList(ctx, filters any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockuserRepo)(nil).GetList), ctx, filters)
}

// RestoreByID mocks base method.
func (m *MockuserRepo) RestoreByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// RestoreByID indicates an expected call of RestoreByID.
func (mr *MockuserRepoMockRecorder) RestoreByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreByID", reflect.TypeOf((*MockuserRepo)(nil).RestoreByID), ctx, id)
}

// SoftDeleteByID mocks base method.
func (m *MockuserRepo) SoftDeleteByID(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SoftDeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// SoftDeleteByID indicates an expected call of SoftDeleteByID.
func (mr *MockuserRepoMockRecorder) SoftDeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SoftDeleteByID", reflect.TypeOf((*MockuserRepo)(nil).SoftDeleteByID), ctx, id)
}

// Update mocks base method.
func (m *MockuserRepo) Update(ctx context.Context, id int64, user auth.Profile) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockuserRepoMockRecorder) Update(ctx, id, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockuserRepo)(nil).Update), ctx, id, user)
}

// MocksubjectEmailStore is a mock of subjectEmailStore interface.
type MocksubjectEmailStore struct {
	ctrl     *gomock.Controller
	recorder *MocksubjectEmailStoreMockRecorder
	isgomock struct{}
}

// MocksubjectEmailStoreMockRecorder is the mock recorder for MocksubjectEmailStore.
type MocksubjectEmailStoreMockRecorder struct {
	mock *MocksubjectEmailStore
}

// NewMocksubjectEmailStore creates a new mock instance.
func NewMocksubjectEmailStore(ctrl *gomock.Controller) *MocksubjectEmailStore {
	mock := &MocksubjectEmailStore{ctrl: ctrl}
	mock.recorder = &MocksubjectEmailStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksubjectEmailStore) EXPECT() *MocksubjectEmailStoreMockRecorder {
	return m.recorder
}

// RequestEmailChange mocks base method.
func (m *MocksubjectEmailStore) RequestEmailChange(ctx context.Context, subjectID goauth.SubjectID, newEmail string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestEmailChange", ctx, subjectID, newEmail)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestEmailChange indicates an expected call of RequestEmailChange.
func (mr *MocksubjectEmailStoreMockRecorder) RequestEmailChange(ctx, subjectID, newEmail any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestEmailChange", reflect.TypeOf((*MocksubjectEmailStore)(nil).RequestEmailChange), ctx, subjectID, newEmail)
}

// SetSubjectStatus mocks base method.
func (m *MocksubjectEmailStore) SetSubjectStatus(ctx context.Context, subjectID goauth.SubjectID, status goauth.SubjectStatus) (goauth.Subject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSubjectStatus", ctx, subjectID, status)
	ret0, _ := ret[0].(goauth.Subject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetSubjectStatus indicates an expected call of SetSubjectStatus.
func (mr *MocksubjectEmailStoreMockRecorder) SetSubjectStatus(ctx, subjectID, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSubjectStatus", reflect.TypeOf((*MocksubjectEmailStore)(nil).SetSubjectStatus), ctx, subjectID, status)
}

// UpdateBasicProfile mocks base method.
func (m *MocksubjectEmailStore) UpdateBasicProfile(ctx context.Context, subjectID goauth.SubjectID, profile goauth.BasicProfile) (goauth.Account, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateBasicProfile", ctx, subjectID, profile)
	ret0, _ := ret[0].(goauth.Account)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateBasicProfile indicates an expected call of UpdateBasicProfile.
func (mr *MocksubjectEmailStoreMockRecorder) UpdateBasicProfile(ctx, subjectID, profile any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateBasicProfile", reflect.TypeOf((*MocksubjectEmailStore)(nil).UpdateBasicProfile), ctx, subjectID, profile)
}
