// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/infrastructure/core/datagrid (interfaces: SQLBuilder)
//
// Generated by this command:
//
//	mockgen -destination=mocks/helpers_mock.gen.go -package=datagridmocks . SQLBuilder
//

// Package datagridmocks is a generated GoMock package.
package datagridmocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSQLBuilder is a mock of SQLBuilder interface.
type MockSQLBuilder[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockSQLBuilderMockRecorder[T]
	isgomock struct{}
}

// MockSQLBuilderMockRecorder is the mock recorder for MockSQLBuilder.
type MockSQLBuilderMockRecorder[T any] struct {
	mock *MockSQLBuilder[T]
}

// NewMockSQLBuilder creates a new mock instance.
func NewMockSQLBuilder[T any](ctrl *gomock.Controller) *MockSQLBuilder[T] {
	mock := &MockSQLBuilder[T]{ctrl: ctrl}
	mock.recorder = &MockSQLBuilderMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSQLBuilder[T]) EXPECT() *MockSQLBuilderMockRecorder[T] {
	return m.recorder
}

// Limit mocks base method.
func (m *MockSQLBuilder[T]) Limit(limit uint64) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Limit", limit)
	ret0, _ := ret[0].(T)
	return ret0
}

// Limit indicates an expected call of Limit.
func (mr *MockSQLBuilderMockRecorder[T]) Limit(limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Limit", reflect.TypeOf((*MockSQLBuilder[T])(nil).Limit), limit)
}

// Offset mocks base method.
func (m *MockSQLBuilder[T]) Offset(offset uint64) T {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Offset", offset)
	ret0, _ := ret[0].(T)
	return ret0
}

// Offset indicates an expected call of Offset.
func (mr *MockSQLBuilderMockRecorder[T]) Offset(offset any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Offset", reflect.TypeOf((*MockSQLBuilder[T])(nil).Offset), offset)
}

// OrderBy mocks base method.
func (m *MockSQLBuilder[T]) OrderBy(orderBys ...string) T {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range orderBys {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "OrderBy", varargs...)
	ret0, _ := ret[0].(T)
	return ret0
}

// OrderBy indicates an expected call of OrderBy.
func (mr *MockSQLBuilderMockRecorder[T]) OrderBy(orderBys ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OrderBy", reflect.TypeOf((*MockSQLBuilder[T])(nil).OrderBy), orderBys...)
}

// Where mocks base method.
func (m *MockSQLBuilder[T]) Where(pred any, args ...any) T {
	m.ctrl.T.Helper()
	varargs := []any{pred}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Where", varargs...)
	ret0, _ := ret[0].(T)
	return ret0
}

// Where indicates an expected call of Where.
func (mr *MockSQLBuilderMockRecorder[T]) Where(pred any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{pred}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Where", reflect.TypeOf((*MockSQLBuilder[T])(nil).Where), varargs...)
}
