// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/http/handlers/permissions (interfaces: listPermissionsUseCase,permissionService)
//
// Generated by this command:
//
//	mockgen -destination=mocks/handler_mock.gen.go -package=permissionsmocks . listPermissionsUseCase,permissionService
//

// Package permissionsmocks is a generated GoMock package.
package permissionsmocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	auth "github.com/assurrussa/goadmin/internal/auth"
)

// MocklistPermissionsUseCase is a mock of listPermissionsUseCase interface.
type MocklistPermissionsUseCase struct {
	ctrl     *gomock.Controller
	recorder *MocklistPermissionsUseCaseMockRecorder
	isgomock struct{}
}

// MocklistPermissionsUseCaseMockRecorder is the mock recorder for MocklistPermissionsUseCase.
type MocklistPermissionsUseCaseMockRecorder struct {
	mock *MocklistPermissionsUseCase
}

// NewMocklistPermissionsUseCase creates a new mock instance.
func NewMocklistPermissionsUseCase(ctrl *gomock.Controller) *MocklistPermissionsUseCase {
	mock := &MocklistPermissionsUseCase{ctrl: ctrl}
	mock.recorder = &MocklistPermissionsUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocklistPermissionsUseCase) EXPECT() *MocklistPermissionsUseCaseMockRecorder {
	return m.recorder
}

// Handle mocks base method.
func (m *MocklistPermissionsUseCase) Handle(ctx context.Context, req auth.ListPermissionsRequest) (auth.ListPermissionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Handle", ctx, req)
	ret0, _ := ret[0].(auth.ListPermissionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Handle indicates an expected call of Handle.
func (mr *MocklistPermissionsUseCaseMockRecorder) Handle(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Handle", reflect.TypeOf((*MocklistPermissionsUseCase)(nil).Handle), ctx, req)
}

// MockpermissionService is a mock of permissionService interface.
type MockpermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockpermissionServiceMockRecorder
	isgomock struct{}
}

// MockpermissionServiceMockRecorder is the mock recorder for MockpermissionService.
type MockpermissionServiceMockRecorder struct {
	mock *MockpermissionService
}

// NewMockpermissionService creates a new mock instance.
func NewMockpermissionService(ctrl *gomock.Controller) *MockpermissionService {
	mock := &MockpermissionService{ctrl: ctrl}
	mock.recorder = &MockpermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpermissionService) EXPECT() *MockpermissionServiceMockRecorder {
	return m.recorder
}

// CreatePermissions mocks base method.
func (m *MockpermissionService) CreatePermissions(ctx context.Context, inputs []auth.CreatePermissionInput) ([]auth.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePermissions", ctx, inputs)
	ret0, _ := ret[0].([]auth.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePermissions indicates an expected call of CreatePermissions.
func (mr *MockpermissionServiceMockRecorder) CreatePermissions(ctx, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePermissions", reflect.TypeOf((*MockpermissionService)(nil).CreatePermissions), ctx, inputs)
}

// EnsurePermissions mocks base method.
func (m *MockpermissionService) EnsurePermissions(ctx context.Context, inputs []auth.CreatePermissionInput) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EnsurePermissions", ctx, inputs)
	ret0, _ := ret[0].(error)
	return ret0
}

// EnsurePermissions indicates an expected call of EnsurePermissions.
func (mr *MockpermissionServiceMockRecorder) EnsurePermissions(ctx, inputs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EnsurePermissions", reflect.TypeOf((*MockpermissionService)(nil).EnsurePermissions), ctx, inputs)
}
