// Code generated by options-gen v0.58.0. DO NOT EDIT.

package notificationsjob

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	"github.com/assurrussa/goadmin/infrastructure/notify"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	repo notificationRepository,
	notifier notify.NotificationManager,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.repo = repo
	o.notifier = notifier
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("repo", _validate_Options_repo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("notifier", _validate_Options_notifier(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_repo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.repo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `repo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_notifier(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.notifier, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `notifier` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
