// Code generated by options-gen v0.58.0. DO NOT EDIT.

package adminpreview

import (
	fmt461e464ebed9 "fmt"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	eventFileAfterProcessService eventFileAfterProcessService,
	adminRepo adminRepository,
	sessionUpdater sessionUpdater,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.eventFileAfterProcessService = eventFileAfterProcessService
	o.adminRepo = adminRepo
	o.sessionUpdater = sessionUpdater
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("eventFileAfterProcessService", _validate_Options_eventFileAfterProcessService(o)))
	errs.Add(errors461e464ebed9.NewValidationError("adminRepo", _validate_Options_adminRepo(o)))
	errs.Add(errors461e464ebed9.NewValidationError("sessionUpdater", _validate_Options_sessionUpdater(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_eventFileAfterProcessService(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.eventFileAfterProcessService, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `eventFileAfterProcessService` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_adminRepo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.adminRepo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `adminRepo` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_sessionUpdater(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.sessionUpdater, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `sessionUpdater` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
