// Code generated by options-gen v0.58.0. DO NOT EDIT.

package server

import (
	"context"
	fmt461e464ebed9 "fmt"
	"time"

	logger "github.com/assurrussa/gologger"
	"github.com/gofiber/fiber/v3"
	"github.com/gofiber/fiber/v3/middleware/cors"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	"github.com/assurrussa/goadmin/infrastructure/fiber/middlewares"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	logger logger.Logger,
	addr string,
	allowOrigins []string,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.serverHeader = "tgmulti"
	o.prefork = false
	o.caseSensitive = true
	o.strictRouting = true
	o.disableStartupMessage = false
	o.maxRequest = 0
	o.expiration, _ = time.ParseDuration("1s")
	o.bodyLimit = 0
	o.allowCredentials = true

	o.logger = logger
	o.addr = addr
	o.allowOrigins = allowOrigins

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithShutdown(opt *Shutdown) OptOptionsSetter {
	return func(o *Options) { o.shutdown = opt }
}

func WithShutdownConnections(opt func(context.Context) error) OptOptionsSetter {
	return func(o *Options) { o.shutdownConnections = opt }
}

func WithReadTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.readTimeout = opt }
}

func WithWriteTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.writeTimeout = opt }
}

func WithIdleTimeout(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.idleTimeout = opt }
}

func WithErrHandler(opt fiber.ErrorHandler) OptOptionsSetter {
	return func(o *Options) { o.errHandler = opt }
}

func WithRegistered(opt FnRegistered) OptOptionsSetter {
	return func(o *Options) { o.registered = opt }
}

func WithHandlers(opt []Handler) OptOptionsSetter {
	return func(o *Options) { o.handlers = opt }
}

func WithServerHeader(opt string) OptOptionsSetter {
	return func(o *Options) { o.serverHeader = opt }
}

func WithPrefork(opt bool) OptOptionsSetter {
	return func(o *Options) { o.prefork = opt }
}

func WithCaseSensitive(opt bool) OptOptionsSetter {
	return func(o *Options) { o.caseSensitive = opt }
}

func WithStrictRouting(opt bool) OptOptionsSetter {
	return func(o *Options) { o.strictRouting = opt }
}

func WithDisableStartupMessage(opt bool) OptOptionsSetter {
	return func(o *Options) { o.disableStartupMessage = opt }
}

func WithMaxRequest(opt int) OptOptionsSetter {
	return func(o *Options) { o.maxRequest = opt }
}

func WithExpiration(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.expiration = opt }
}

func WithBodyLimit(opt int) OptOptionsSetter {
	return func(o *Options) { o.bodyLimit = opt }
}

func WithAllowHeaders(opt []string) OptOptionsSetter {
	return func(o *Options) { o.allowHeaders = opt }
}

func WithAllowMethods(opt []string) OptOptionsSetter {
	return func(o *Options) { o.allowMethods = opt }
}

func WithAllowCredentials(opt bool) OptOptionsSetter {
	return func(o *Options) { o.allowCredentials = opt }
}

func WithCors(opt *cors.Config) OptOptionsSetter {
	return func(o *Options) { o.cors = opt }
}

func WithTlsCert(opt string) OptOptionsSetter {
	return func(o *Options) { o.tlsCert = opt }
}

func WithTlsKey(opt string) OptOptionsSetter {
	return func(o *Options) { o.tlsKey = opt }
}

func WithMiddlewares(opt []fiber.Handler) OptOptionsSetter {
	return func(o *Options) { o.middlewares = opt }
}

func WithSkipFnLogger(opt *middlewares.RequestLoggerConfig) OptOptionsSetter {
	return func(o *Options) { o.skipFnLogger = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	errs.Add(errors461e464ebed9.NewValidationError("addr", _validate_Options_addr(o)))
	errs.Add(errors461e464ebed9.NewValidationError("allowOrigins", _validate_Options_allowOrigins(o)))
	return errs.AsError()
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_addr(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.addr, "required,hostname_port"); err != nil {
		return fmt461e464ebed9.Errorf("field `addr` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_allowOrigins(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.allowOrigins, "required,min=1"); err != nil {
		return fmt461e464ebed9.Errorf("field `allowOrigins` did not pass the test: %w", err)
	}
	return nil
}
