// Code generated by options-gen v0.58.0. DO NOT EDIT.

package csrf

import (
	fmt461e464ebed9 "fmt"
	"time"

	logger "github.com/assurrussa/gologger"
	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	appDomain string,
	secretKey string,
	allowedOrigins []string,
	logger logger.Logger,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.tokenTTL, _ = time.ParseDuration("24h")

	o.appDomain = appDomain
	o.secretKey = secretKey
	o.allowedOrigins = allowedOrigins
	o.logger = logger

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func WithTokenTTL(opt time.Duration) OptOptionsSetter {
	return func(o *Options) { o.tokenTTL = opt }
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("appDomain", _validate_Options_appDomain(o)))
	errs.Add(errors461e464ebed9.NewValidationError("secretKey", _validate_Options_secretKey(o)))
	errs.Add(errors461e464ebed9.NewValidationError("allowedOrigins", _validate_Options_allowedOrigins(o)))
	errs.Add(errors461e464ebed9.NewValidationError("logger", _validate_Options_logger(o)))
	return errs.AsError()
}

func _validate_Options_appDomain(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.appDomain, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `appDomain` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_secretKey(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.secretKey, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `secretKey` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_allowedOrigins(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.allowedOrigins, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `allowedOrigins` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_logger(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.logger, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `logger` did not pass the test: %w", err)
	}
	return nil
}
