// Code generated by options-gen v0.58.0. DO NOT EDIT.

package jobsfailedrepo

import (
	fmt461e464ebed9 "fmt"

	errors461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/errors"
	validator461e464ebed9 "github.com/kazhuravlev/options-gen/pkg/validator"

	outbox "github.com/assurrussa/goadmin/infrastructure/outbox"
)

type OptOptionsSetter func(o *Options)

func NewOptions(
	pgsql outbox.StoragePgsqlClient,
	repo jobsFailedRepository,
	options ...OptOptionsSetter,
) Options {
	var o Options

	// Setting defaults from field tag (if present)

	o.pgsql = pgsql
	o.repo = repo

	for _, opt := range options {
		opt(&o)
	}
	return o
}

func (o *Options) Validate() error {
	errs := new(errors461e464ebed9.ValidationErrors)
	errs.Add(errors461e464ebed9.NewValidationError("pgsql", _validate_Options_pgsql(o)))
	errs.Add(errors461e464ebed9.NewValidationError("repo", _validate_Options_repo(o)))
	return errs.AsError()
}

func _validate_Options_pgsql(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.pgsql, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `pgsql` did not pass the test: %w", err)
	}
	return nil
}

func _validate_Options_repo(o *Options) error {
	if err := validator461e464ebed9.GetValidatorFor(o).Var(o.repo, "required"); err != nil {
		return fmt461e464ebed9.Errorf("field `repo` did not pass the test: %w", err)
	}
	return nil
}
