// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/assurrussa/goadmin/outbox/preview_detach (interfaces: adminRepository,eventFileAfterProcessService,sessionUpdater)
//
// Generated by this command:
//
//	mockgen -destination=mocks/job_mock.gen.go -package=adminpreviewmocks . adminRepository,eventFileAfterProcessService,sessionUpdater
//

// Package adminpreviewmocks is a generated GoMock package.
package adminpreviewmocks

import (
	context "context"
	reflect "reflect"

	host "github.com/assurrussa/gouploads/host"
	gomock "go.uber.org/mock/gomock"

	identity "github.com/assurrussa/goadmin/internal/identity"
	models "github.com/assurrussa/goadmin/models"
)

// MockadminRepository is a mock of adminRepository interface.
type MockadminRepository struct {
	ctrl     *gomock.Controller
	recorder *MockadminRepositoryMockRecorder
	isgomock struct{}
}

// MockadminRepositoryMockRecorder is the mock recorder for MockadminRepository.
type MockadminRepositoryMockRecorder struct {
	mock *MockadminRepository
}

// NewMockadminRepository creates a new mock instance.
func NewMockadminRepository(ctrl *gomock.Controller) *MockadminRepository {
	mock := &MockadminRepository{ctrl: ctrl}
	mock.recorder = &MockadminRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockadminRepository) EXPECT() *MockadminRepositoryMockRecorder {
	return m.recorder
}

// GetByUUID mocks base method.
func (m *MockadminRepository) GetByUUID(ctx context.Context, id identity.UserID) (models.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUUID", ctx, id)
	ret0, _ := ret[0].(models.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUUID indicates an expected call of GetByUUID.
func (mr *MockadminRepositoryMockRecorder) GetByUUID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUUID", reflect.TypeOf((*MockadminRepository)(nil).GetByUUID), ctx, id)
}

// UpdateAdmin mocks base method.
func (m *MockadminRepository) UpdateAdmin(ctx context.Context, id int64, admin models.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateAdmin", ctx, id, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateAdmin indicates an expected call of UpdateAdmin.
func (mr *MockadminRepositoryMockRecorder) UpdateAdmin(ctx, id, admin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateAdmin", reflect.TypeOf((*MockadminRepository)(nil).UpdateAdmin), ctx, id, admin)
}

// UpdatePreview mocks base method.
func (m *MockadminRepository) UpdatePreview(ctx context.Context, admin models.Admin, fileID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreview", ctx, admin, fileID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreview indicates an expected call of UpdatePreview.
func (mr *MockadminRepositoryMockRecorder) UpdatePreview(ctx, admin, fileID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreview", reflect.TypeOf((*MockadminRepository)(nil).UpdatePreview), ctx, admin, fileID)
}

// MockeventFileAfterProcessService is a mock of eventFileAfterProcessService interface.
type MockeventFileAfterProcessService struct {
	ctrl     *gomock.Controller
	recorder *MockeventFileAfterProcessServiceMockRecorder
	isgomock struct{}
}

// MockeventFileAfterProcessServiceMockRecorder is the mock recorder for MockeventFileAfterProcessService.
type MockeventFileAfterProcessServiceMockRecorder struct {
	mock *MockeventFileAfterProcessService
}

// NewMockeventFileAfterProcessService creates a new mock instance.
func NewMockeventFileAfterProcessService(ctrl *gomock.Controller) *MockeventFileAfterProcessService {
	mock := &MockeventFileAfterProcessService{ctrl: ctrl}
	mock.recorder = &MockeventFileAfterProcessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockeventFileAfterProcessService) EXPECT() *MockeventFileAfterProcessServiceMockRecorder {
	return m.recorder
}

// HandleAfterProcess mocks base method.
func (m *MockeventFileAfterProcessService) HandleAfterProcess(ctx context.Context, payload string, fnCall host.AfterProcessFunc) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleAfterProcess", ctx, payload, fnCall)
	ret0, _ := ret[0].(error)
	return ret0
}

// HandleAfterProcess indicates an expected call of HandleAfterProcess.
func (mr *MockeventFileAfterProcessServiceMockRecorder) HandleAfterProcess(ctx, payload, fnCall any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleAfterProcess", reflect.TypeOf((*MockeventFileAfterProcessService)(nil).HandleAfterProcess), ctx, payload, fnCall)
}

// MocksessionUpdater is a mock of sessionUpdater interface.
type MocksessionUpdater struct {
	ctrl     *gomock.Controller
	recorder *MocksessionUpdaterMockRecorder
	isgomock struct{}
}

// MocksessionUpdaterMockRecorder is the mock recorder for MocksessionUpdater.
type MocksessionUpdaterMockRecorder struct {
	mock *MocksessionUpdater
}

// NewMocksessionUpdater creates a new mock instance.
func NewMocksessionUpdater(ctrl *gomock.Controller) *MocksessionUpdater {
	mock := &MocksessionUpdater{ctrl: ctrl}
	mock.recorder = &MocksessionUpdaterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MocksessionUpdater) EXPECT() *MocksessionUpdaterMockRecorder {
	return m.recorder
}

// UpdatePreview mocks base method.
func (m *MocksessionUpdater) UpdatePreview(ctx context.Context, sessionID string, previewID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreview", ctx, sessionID, previewID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreview indicates an expected call of UpdatePreview.
func (mr *MocksessionUpdaterMockRecorder) UpdatePreview(ctx, sessionID, previewID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreview", reflect.TypeOf((*MocksessionUpdater)(nil).UpdatePreview), ctx, sessionID, previewID)
}
